name: Build Docker Image For Linux AMD64

env:
  dockerhub_repository: "hapxs-surl/hapxs-surl"
  dockerhub_tag: "main"

on:
  push:
    branches:
      - main

jobs:
  dockerhub-build-push:
    runs-on: ubuntu-latest
    if: (github.actor == 'happy-clo' || github.actor == 'Happy-clo' || github.actor == 'actions-user' || github.actor == 'hapxscom' || github.actor == 'devhappys') && !contains(github.event.head_commit.message, 'npm(deps):')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ env.dockerhub_repository }}:${{ env.dockerhub_tag }}
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.dockerhub_repository }}
      
      - name: Install Node.js dependencies
        run: |
          npm install ssh2 dotenv axios

      - name: Set script permissions
        run: |
          chmod +x .github/workflows/deploy_image.js

      - name: Run deployment script
        if: github.event_name != 'pull_request'
        env:
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CONTAINER_NAMES: ${{ secrets.CONTAINER_NAMES }}
          IMAGE_URL: happyclo/tts-node:${{ steps.meta.outputs.short_sha }}-amd64
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          node .github/workflows/deploy_image.js